### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by Azshurith** [aromaa/AdobeAIR-DiscordRPC#1]
C:\Users\Me\Downloads\AdobeAIR-DiscordRPC-master>"C:\Program Files\Adobe\Adobe Animate 2020\AIR\AIR 33.0\bin\adl" -package -target ane DiscordRPC.ane AS3\extension.xml -swc DiscordRPC-Windows-x86.swc -platform Windows-x86 -C Platform/Windows-x86 .

It gives "application descriptor not found"

**Comment by aromaa** [comment]
You need to have AIR Developer Tool (ADT) installed. Also there's a compiled build available in the releases.

**Comment by Azshurith** [comment]
Ahhh, thanks a lot!
