### ISSUE TITLE
Discord RPC Buttons Update

### ISSUE THREAD

**Issue by Azshurith** [aromaa/AdobeAIR-DiscordRPC#3]
Will you release a released version with this update? Would be happy to have one. 
https://www.youtube.com/watch?v=-WBQuAlF_DE

buttons: [
	{label: '', url:''},
	{label: '', url:''},
]

**Comment by aromaa** [comment]
The Discord SDK doesn't expose the buttons and they aren't intended to be changed. Looks like that you can change them if you bypass the SDK by sending the activity status JSON by yourself.
